apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: velotio-ajinkya
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: velotio
  template:
    metadata:
      labels:
        app: velotio
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.8
        ports:
          - name: web
            containerPort: 80
            protocol: TCP