apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: velotio-ajinkya
  name: velotio-cronjob
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            command:  ["/bin/sh", "-c", "date; echo Hello world"]
          restartPolicy: OnFailure
